from ROOT import TH1F, TFile, TCanvas, gStyle, TLegend, TLine, gPad
gStyle.SetOptStat(False)
canvas = TCanvas('canvas','canvas',850,800)
fFilenew = TFile("BDT.root")
hmvaS = fFilenew.Get("mvaS")
hmvaB = fFilenew.Get("mvaB")
hmvaSEff = fFilenew.Get("mvaEff")
print hmvaSEff.GetBinContent(100)
#hmvaS.SetMarkerStyle(0)
hmvaS.SetLineColor(2)
hmvaS.SetFillColor(10)
#hmvaS.SetFillStyle(3002)
#hmvaS.SetFillColor(1)
#hmvaB.SetMarkerStyle(0)
hmvaB.SetLineColor(4)
hmvaB.SetMinimum(0)
#hmvaB.SetFillStyle(3002)
#hmvaB.SetFillColor(1)
hmvaS.SetTitle(" ")
hmvaS.SetXTitle("BDT Discriminator")
hmvaS.SetYTitle("Events per 0.01 BDT Discriminator")
hmvaS.Draw('HIST')
hmvaB.Draw("HIST,same")
legend = TLegend(0.65, 0.65, .85, .85)
legend.SetBorderSize(0)
legend.AddEntry(hmvaS,"Signal")
legend.AddEntry(hmvaB,"Background")
legend.Draw()
print canvas.GetUymax()
print canvas.GetUymin()
gPad.Modified()
gPad.Update()
line = TLine(0,canvas.GetUymin(),0,canvas.GetUymax())
line.SetLineStyle(9)
#line.SetNDC(True)
line.Draw()
canvas.SaveAs("MVA.png")
