nohup root -b -q 'TMVAClassification.C("")' >& BDTroot/test.log & 
nohup root -b -q 'TMVAClassification.C("JetAbsoluteUp_")' >& BDTroot/JetAbsoluteUp.log & 
nohup root -b -q 'TMVAClassification.C("JetAbsoluteDown_")' >& BDTroot/JetAbsoluteDown.log & 
nohup root -b -q 'TMVAClassification.C("JetAbsoluteyearUp_")' >& BDTroot/JetAbsoluteyearUp.log & 
nohup root -b -q 'TMVAClassification.C("JetAbsoluteyearDown_")' >& BDTroot/JetAbsoluteyearDown.log & 
nohup root -b -q 'TMVAClassification.C("JetBBEC1Up_")' >& BDTroot/JetBBEC1Up.log & 
nohup root -b -q 'TMVAClassification.C("JetBBEC1Down_")' >& BDTroot/JetBBEC1Down.log & 
nohup root -b -q 'TMVAClassification.C("JetBBEC1yearUp_")' >& BDTroot/JetBBEC1yearUp.log & 
nohup root -b -q 'TMVAClassification.C("JetBBEC1yearDown_")' >& BDTroot/JetBBEC1yearDown.log & 
nohup root -b -q 'TMVAClassification.C("JetFlavorQCDUp_")' >& BDTroot/JetFlavorQCDUp.log & 
nohup root -b -q 'TMVAClassification.C("JetFlavorQCDDown_")' >& BDTroot/JetFlavorQCDDown.log & 
nohup root -b -q 'TMVAClassification.C("JetEC2Up_")' >& BDTroot/JetEC2Up.log & 
nohup root -b -q 'TMVAClassification.C("JetEC2Down_")' >& BDTroot/JetEC2Down.log & 
nohup root -b -q 'TMVAClassification.C("JetEC2yearUp_")' >& BDTroot/JetEC2yearUp.log & 
nohup root -b -q 'TMVAClassification.C("JetEC2yearDown_")' >& BDTroot/JetEC2yearDown.log & 
nohup root -b -q 'TMVAClassification.C("JetHFUp_")' >& BDTroot/JetHFUp.log & 
nohup root -b -q 'TMVAClassification.C("JetHFDown_")' >& BDTroot/JetHFDown.log & 
nohup root -b -q 'TMVAClassification.C("JetHFyearUp_")' >& BDTroot/JetHFyearUp.log & 
nohup root -b -q 'TMVAClassification.C("JetHFyearDown_")' >& BDTroot/JetHFyearDown.log & 
nohup root -b -q 'TMVAClassification.C("JetRelativeBalUp_")' >& BDTroot/JetRelativeBalUp.log & 
nohup root -b -q 'TMVAClassification.C("JetRelativeBalDown_")' >& BDTroot/JetRelativeBalDown.log & 
nohup root -b -q 'TMVAClassification.C("JetRelativeSampleUp_")' >& BDTroot/JetRelativeSampleUp.log & 
nohup root -b -q 'TMVAClassification.C("JetRelativeSampleDown_")' >& BDTroot/JetRelativeSampleDown.log & 
nohup root -b -q 'TMVAClassification.C("JERUp_")' >& BDTroot/JERUp.log & 
nohup root -b -q 'TMVAClassification.C("JERDown_")' >& BDTroot/JERDown.log & 
nohup root -b -q 'TMVAClassification.C("UnclusteredEnUp_")' >& BDTroot/UnclusteredEnUp.log & 
nohup root -b -q 'TMVAClassification.C("UnclusteredEnDown_")' >& BDTroot/UnclusteredEnDown.log & 
nohup root -b -q 'TMVAClassification.C("UesCHARGEDUp_")' >& BDTroot/UesCHARGEDUp.log & 
nohup root -b -q 'TMVAClassification.C("UesCHARGEDDown_")' >& BDTroot/UesCHARGEDDown.log & 
nohup root -b -q 'TMVAClassification.C("UesECALUp_")' >& BDTroot/UesECALUp.log & 
nohup root -b -q 'TMVAClassification.C("UesECALDown_")' >& BDTroot/UesECALDown.log & 
nohup root -b -q 'TMVAClassification.C("UesHCALUp_")' >& BDTroot/UesHCALUp.log & 
nohup root -b -q 'TMVAClassification.C("UesHCALDown_")' >& BDTroot/UesHCALDown.log & 
nohup root -b -q 'TMVAClassification.C("UesHFUp_")' >& BDTroot/UesHFUp.log & 
nohup root -b -q 'TMVAClassification.C("UesHFDown_")' >& BDTroot/UesHFDown.log & 
nohup root -b -q 'TMVAClassification.C("puUp_")' >& BDTroot/puUp.log & 
nohup root -b -q 'TMVAClassification.C("puDown_")' >& BDTroot/puDown.log & 
nohup root -b -q 'TMVAClassification.C("bTagUp_")' >& BDTroot/bTagUp.log & 
nohup root -b -q 'TMVAClassification.C("bTagDown_")' >& BDTroot/bTagDown.log & 
nohup root -b -q 'TMVAClassification.C("pfUp_")' >& BDTroot/pfUp.log & 
nohup root -b -q 'TMVAClassification.C("pfDown_")' >& BDTroot/pfDown.log & 
nohup root -b -q 'TMVAClassification.C("mes1p2Up_")' >& BDTroot/mes1p2Up.log & 
nohup root -b -q 'TMVAClassification.C("mes1p2Down_")' >& BDTroot/mes1p2Down.log & 
nohup root -b -q 'TMVAClassification.C("mes2p1Up_")' >& BDTroot/mes2p1Up.log & 
nohup root -b -q 'TMVAClassification.C("mes2p1Down_")' >& BDTroot/mes2p1Down.log & 
nohup root -b -q 'TMVAClassification.C("mes2p4Up_")' >& BDTroot/mes2p4Up.log & 
nohup root -b -q 'TMVAClassification.C("mes2p4Down_")' >& BDTroot/mes2p4Down.log & 
nohup root -b -q 'TMVAClassification.C("eesUp_")' >& BDTroot/eesUp.log & 
nohup root -b -q 'TMVAClassification.C("eesDown_")' >& BDTroot/eesDown.log & 
